Implementation
wearesho-team/yii2-phonet pull request #1
Opened 2019-01-25 17:10 UTC by KartaviK

2019-01-28 13:53 UTC, sashabeton requested changes

2019-01-28 13:53 UTC, sashabeton commented on src/Panel/HandlerPanel.php
> +        return isset($_POST[$param]) || \array_key_exists($param, $_POST) ? $_POST[$param] : null;
Use `$this->request->post()`

2019-01-28 16:17 UTC, Horat1us reviewed
Необходимо добавить класс, абстрактно реализующий Identity (без метода поиска)

2019-01-28 16:17 UTC, Horat1us commented on src/IdentityInterface.php
> +    public static function findBy(string $number, ?string $request, ?string $trunk): ?IdentityInterface;
Какое поведение будет у этой функции? С каким аргументов повезет по тому и искать? По этому объявлению я не понимаю, как реализовать интерфейс.

2019-01-29 14:42 UTC, KartaviK commented on src/IdentityInterface.php
> +    public static function findBy(string $number, ?string $request, ?string $trunk): ?IdentityInterface;
Количество аргументов сокращено, добавлены описания

2019-01-29 14:52 UTC, KartaviK commented
> Необходимо добавить класс, абстрактно реализующий Identity (без метода поиска)

Он должен наследоваться от yii, или это чисто отдельный абстрактный класс?

2019-03-12 13:05 UTC, Horat1us approved these changes

2019-03-12 13:05 UTC, merged